services:
  - type: web
    name: pitch-ia
    env: go
    buildCommand: go mod download && go build -o pitch .
    startCommand: ./pitch
    envVars:
      - key: PORT
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    plan: starter

